// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBBX7XMGEWas286oWka55_gG0ZMjnqxPs',
    appId: '1:208154502151:web:17f5f310a8b72447fc36a2',
    messagingSenderId: '208154502151',
    projectId: 'groceryapp-ad74e',
    authDomain: 'groceryapp-ad74e.firebaseapp.com',
    storageBucket: 'groceryapp-ad74e.appspot.com',
    measurementId: 'G-DQR98TKQ70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJI4MjsU6ONOj8Z_9K2J0UGNhZxxZZVaM',
    appId: '1:208154502151:android:86385fed069db007fc36a2',
    messagingSenderId: '208154502151',
    projectId: 'groceryapp-ad74e',
    storageBucket: 'groceryapp-ad74e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOzvoPHPA-RGG-Clx_K6oL6j8TtYhMZU',
    appId: '1:208154502151:ios:23cfc99ac47feb66fc36a2',
    messagingSenderId: '208154502151',
    projectId: 'groceryapp-ad74e',
    storageBucket: 'groceryapp-ad74e.appspot.com',
    androidClientId: '208154502151-1ihs1sgftjse9bdko2m1u55p2u1q0ov0.apps.googleusercontent.com',
    iosClientId: '208154502151-vnqo8bbe0pdr1c0ue1n09rkp58n13cfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOzvoPHPA-RGG-Clx_K6oL6j8TtYhMZU',
    appId: '1:208154502151:ios:23cfc99ac47feb66fc36a2',
    messagingSenderId: '208154502151',
    projectId: 'groceryapp-ad74e',
    storageBucket: 'groceryapp-ad74e.appspot.com',
    androidClientId: '208154502151-1ihs1sgftjse9bdko2m1u55p2u1q0ov0.apps.googleusercontent.com',
    iosClientId: '208154502151-vnqo8bbe0pdr1c0ue1n09rkp58n13cfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBBX7XMGEWas286oWka55_gG0ZMjnqxPs',
    appId: '1:208154502151:web:6e0877f7eed67fcdfc36a2',
    messagingSenderId: '208154502151',
    projectId: 'groceryapp-ad74e',
    authDomain: 'groceryapp-ad74e.firebaseapp.com',
    storageBucket: 'groceryapp-ad74e.appspot.com',
    measurementId: 'G-N5S2MMS8YC',
  );
}
